const SUPPORTED_LANGUAGES = ["en", "ko"]
const LANGUAGE_QUERY_STRING_KEY = 'lng'
const LANGUAGE_COOKIE_KEY = 'cffelang'

export {
  SUPPORTED_LANGUAGES,
  LANGUAGE_QUERY_STRING_KEY,
  LANGUAGE_COOKIE_KEY
}
